# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c855b202e7dd04301d1e1282508433f3626f7c1430144eccf7f1ed12d69ec625375ffb1a462bf3c868d7491a4949c609c73651f91bb0e7a5988ba707a808ff6d

test:
  secret_key_base: 0c32d972423afd97e1e3931600daebd4537d388b00cb025efe05d7ad8ba70790e3cb8b0f7f3e8d49376fc629f7c2cc0964b8480ea5c435a4db38d1b563b8e843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
